- Makefile
- cmd/provider/main.go
- go.mod
- go.sum
- internal/controller/template.go
- internal/controller/workspace/workspace.go
- package/crds/tf.crossplane.io_workspaces.yaml
This PR adds a `--poll` flag to make the poll (i.e. speculative requeue) interval configurable. This involved bumping crossplane-runtime to v0.14, and I decided to bump the build submodule while I was in there.
I have:
This is just plumbing, so I've just run `make reviewable` for now.
> Make poll interval configurable

- cmd/provider/main.go
- internal/controller/template.go
- internal/controller/workspace/workspace.go
This probably needs to be tuned in relation to the poll interval at some point; I would imagine that new reconciles that are queued while one is still happening would fail due to the Terraform state lock.
I have:
I've started the provider with `--timeout=1s` and applied the inline example. I see:
```console
Warning  CannotConnectToProvider  3s (x4 over 7s)    managed/workspace.tf.crossplane.io  cannot initialize Terraform configuration: signal: killed
```
When I bump the timeout to 30 seconds I see reconciles proceeding successfully.
> Make the reconcile timeout configurable

- internal/controller/workspace/workspace.go
- internal/controller/workspace/workspace_test.go
- internal/terraform/terraform.go
- internal/terraform/terraform_harness_test.go
Previously we assumed the workspace was not up-to-date during the observe phase and went straight to invoking terraform apply. The rationale was we might as well go straight to trying to apply, because terraform will just abort without making any changes if none are needed. The downside of this approach is that the resource would act as if it were constantly out-of-date, emitting a spurious update event on every reconcile.
I have:
I've run `terraform_harness_test.go` which is effectively an integration test. I've also tested this out using `examples/workspace-inline.yaml` and confirmed that the provider now only updates workspaces when I actually change them.
> Use `terraform plan` to determine whether the workspace is up-to-date 

- cluster/images/provider-terraform-controller/Dockerfile
As of Crossplane v1.3.0 this is the UID the package manager runs all controllers as, so we need to make sure that user has access to the /tf directory.
I have:
I've built this image locally and confirmed it can create workdirs under the `/tf` directory when installed by the Crossplane package manager without any special `ControllerConfig`.
> Grant UID 2000 access to do Terraform things

- README.md
- apis/v1alpha1/workspace_types.go
- examples/workspace-remote.yaml
- internal/controller/workspace/workspace.go
- internal/controller/workspace/workspace_test.go
- package/crds/tf.crossplane.io_workspaces.yaml
I had not used this functionality in a while; it turns out Terraform refuses to initialize a remote workspace when there are files in place. Unfortunately it also sometimes needs those files. I think we will need a better solution in future - e.g. using go-getter or similar to separately fetch the module.
I have:
> Fix support for remote modules

- internal/controller/workspace/workspace.go
* Use Data instead of BinaryData(which is used for non-UTF content
according to the API spec, see https://pkg.go.dev/k8s.io/api/core/v1#ConfigMap)
to correctly populated the target varfile
* Fixes #25
Signed-off-by: Yury Tsarev <yury.tsarev@absa.africa>
Fixes #25
I have:
End-to-end tested on the real cluster setup
> Fix ConfigMap based VarFile population

- .github/workflows/ci.yml
- examples/workspace-inline.yaml
- examples/workspace-remote.yaml
- internal/controller/workspace/workspace.go
* The git checkout was failing without referencing subdirectory like
`git::https://example.com/network.git//modules/vpc`
* Fix it by not pre-creating working directory and
let go-getter do it during intial checkout, otherwise it will fail.
* Update examples
* Fixes #29
Fixes #29 
I have:
e2e workspace checkout with
```
module: git::https://github.com/terraform-aws-modules/terraform-aws-security-group
```
> Fix root git repository checkout

- apis/v1alpha1/workspace_types.go
- package/crds/tf.crossplane.io_workspaces.yaml
Adds the READY and SYNCED status indicators to the output:
```
NAME    READY   SYNCED   AGE
test1   True    True     84s
```
I have:
Tested in a Kind cluster
> Add the Ready and Synced status indicators to output

- .golangci.yml
This PR enables golint to catch errors assignment to blank identifier
Relates to  review of #52 implementation
I have:
Checked that it is green on the current `main`
```
make lint
11:47:27 [ .. ] verify dependencies have expected content
all modules verified
11:47:28 [ OK ] go modules dependencies verified
11:47:28 [ .. ] golangci-lint
11:47:29 [ OK ] golangci-lint
```
Checked that it is catching the error assignment to blank identifier when it is present in the code
```
11:42:40 [ .. ] golangci-lint
internal/controller/workspace/workspace.go:331:2: Error return value of `c.kube.List` is not checked (errcheck)
_ = c.kube.List(ctx, sl, client.MatchingLabels(labels))
^
internal/controller/workspace/workspace.go:334:3: Error return value of …
```
> Enable linter to catch errors assignment to blank identifier

- internal/controller/workspace/workspace.go
- internal/controller/workspace/workspace_test.go
Added code to the Delete method to clean up any Secret or Lease objects that were used by the Terraform
Kubernetes back end to store tfstate information.
Fixes #40 
I have:
Tested in an EKS deployment - verified that deleting a Workspace that is using a Kubernetes backend also deletes the associated Secret and Lease.
> Cleanup Secret and Lease objects from tfstate

- internal/controller/workspace/workspace.go
- internal/controller/workspace/workspace_test.go
- internal/terraform/terraform.go
- internal/terraform/terraform_harness_test.go
Refactor the delete handling code to use "terraform workspace delete" to remove the workspace cleanly.
Fixes #55 
I have:
The code ran in my local environment for a week with no issues.
> Refactor delete handling to remove the workspace

- internal/terraform/terraform.go
* Apparently read only 'terraform plan' locks the state
* It leads to state locking on every reconciliation loop of the
specific Workspace
* Avoid locking by '-lock=false' for `plan` only, we are still locking
on `apply`
* This change is partial mitigation of #46
Related terraform upstream discussions:
* https://github.com/hashicorp/terraform/issues/28130
* https://discuss.hashicorp.com/t/why-does-a-plan-lock-the-state-file/3520/10
I have:
```
$ cat examples/managed-resources/provider-terraform/awsIAMRole.yaml
apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
name: iamrole-terraform-test
spec:
forProvider:
module: git::https://github.com/ytsarev/provider-terraform-test-module.git//iam?ref=main
source: Remote
vars:
- key: iamRole …
```
> Do not lock state on Diff/Plan

- internal/controller/workspace/workspace.go
- internal/controller/workspace/workspace_test.go
Include outputs in the condition that determines whether the resource exists.
This will handle "calculation only" workspaces that do not create anything but still have outputs.
Fixes #71 
I have:
Verified in our testing environment with Workspaces that were previously being "recreated" on every reconciliation
> Include outputs in test for ResourceExists  (#71)

- internal/controller/workspace/workspace.go
- internal/controller/workspace/workspace_test.go
Move the git-credentials env var code out of the Remote module source block so that the GIT_CRED_DIR env variable is available to both inline and remote sources
Fixes #74 
I have:
This has been run in our dev environment and has additional unit test added
> Make git credentials available to inline and remote (#74)

- README.md
- apis/v1alpha1/types.go
- examples/aws-eks-irsa-seup.yaml
- package/crds/tf.crossplane.io_providerconfigs.yaml
* Adding some documentation and an example regarding how to setup the provider using AWS IRSA.
* Fix a bug where `InjectedIdentity` was wrongly advertised as a valid credentials source for the provider config.
* Added an extra commit with some linter fixes to the README, I can revert it if you don't agree with my linter setup...
Fixes #70 
I have:
I have manually tested the setup in a real EKS cluster.
> Injected identity

- README.md
- apis/v1alpha1/workspace_types.go
- internal/controller/workspace/workspace.go
- internal/controller/workspace/workspace_test.go
- package/crds/tf.crossplane.io_workspaces.yaml
Fixes #83
I have:
Used https://github.com/ytsarev/provider-terraform-test-module for e2e testing
```
$ cat tf.yaml
apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
name: relative-path-test
spec:
forProvider:
module: git::https://github.com/ytsarev/provider-terraform-test-module.git
source: Remote
entrypoint: relative-path-iam
vars:
- key: iamRole
value: relative-path-test
$ cat tf-regression.yaml
apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
name: regression-test
spec:
forProvider:
module: git::https://github.com/ytsarev/provider-terraform-test-module.git//iam?ref=main
source: Remote
vars:
- key: iamRole
value: regression-test
k apply -f tf.yaml
k apply -f tf-regression.yaml
k get -f tf-regression.yaml
NAME …
```
> Introduce entrypoint to enable working with relative path modules

- examples/observe-only-composition/README.md
- examples/observe-only-composition/composition.yaml
- examples/observe-only-composition/definition.yaml
- examples/observe-only-composition/xsubnet.yaml
Provides a temporary solution to the observe-only problem using provider-terraform.
Relates to https://github.com/crossplane/crossplane/issues/1722
I have:
```
k apply -f xsubnet.yaml
k get xsubnets.aws.platformref.upbound.io
NAME                           READY   COMPOSITION                           AGE
subnet-with-observe-only-vpc   True    xsubnets.aws.platformref.upbound.io   29m
k get workspace
NAME                                 READY   SYNCED   AGE
subnet-with-observe-only-vpc-x6cfr   True    True     29m
k get subnet.ec2.aws
NAME                                 READY   SYNCED   EXTERNAL-NAME              AGE
subnet-with-observe-only-vpc-rprxx   True    True     subnet-064b90776eafffcfe   24m
```
[contribution process]: …
> Example of observe-only workaround experiment

- apis/v1alpha1/types.go
- apis/v1alpha1/workspace_types.go
- package/crds/tf.crossplane.io_providerconfigs.yaml
- package/crds/tf.crossplane.io_providerconfigusages.yaml
- package/crds/tf.crossplane.io_workspaces.yaml
Include provider CRDs into the relevant API categories. 
Fixes #114
Enables getting Workspaces in the output of `kubectl get managed` and `kubectl get terraform`
Similar changes to `ProviderConfig` and `ProviderConfigUsage` for getting into `kubectl get provider` and `kubectl get terraform` output
I have:
```console
k apply -f examples/workspace-remote.yaml
workspace.tf.crossplane.io/example-remote configured
k get managed
NAME                                        READY   SYNCED   AGE
workspace.tf.crossplane.io/example-remote           False    5m21s
k get terraform
NAME                                                                        AGE     CONFIG-NAME   RESOURCE-KIND   RESOURCE-NAME …
```
> Add categories to provider CRDs

- .gitignore
- Makefile
- cluster/images/provider-terraform/Dockerfile
- internal/controller/workspace/workspace.go
* Fix `make run` failing target
* Introduce `XP_TF_DIR` env variable to control main `tfDir` location
* Use `KUBE_CONFIG_PATH` from https://developer.hashicorp.com/terraform/language/settings/backends/kubernetes to handle local out-of-cluster controller execution
I have:
Assuming following `default` `ProviderConfig`
```
k get providerconfig.tf default -o yaml | k neat
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
name: default
spec:
configuration: |
terraform {
backend "kubernetes" {
secret_suffix     = "providerconfig-terraform-aws"
namespace         = "upbound-system"
#in_cluster_config = true
}
}
provider "aws" {
shared_credentials_file = "aws-creds.ini"
region = "eu-central-1"
}
credentials:
- filename: …
```
> Fix `make run` for local development

- cluster/images/provider-terraform/Dockerfile
- cluster/images/provider-terraform/Makefile
* Update to latest build submodule
* Use curl instead of wget to retrieve image
* Allow BUILD_ARGS from environment to support proxy variables
Updated the Dockerfile to install curl and use it in place of wget - curl works with
the http_proxy and https_proxy environment variables
Updated the Makefile to allow external BUILD_ARGS to be passed in so that the env variables can be passed
into the docker build command without modifying the Dockerfile
For example:   make BUILD_ARGS="--build-arg http_proxy=http://my.proxy.com --build-arg https_proxy=http://my.proxy.com"
Fixes #130 
I have:
Generated an image and running it in our development environment
> Fix make when behind http proxy

- cluster/images/provider-terraform/Dockerfile
- internal/controller/workspace/workspace.go
- internal/controller/workspace/workspace_test.go
- internal/terraform/terraform.go
* Remove setenv of TF_PLUGIN_CACHE_DIR for each Workspace connect
* Set TF_PLUGIN_CACHE_DIR env var in Dockerfile
* Unset TF_PLUGIN_CACHE_DIR in the CLI process environment when pluginCache is false
* Set TF_IN_AUTOMATION env var in Dockerfile
Fixes #139 
I have:
Tested in a development cluster with 100+ workspaces
> Refactor plugin cache implementation

- docs/monolith/Troubleshooting.md
Adds troubleshooting info that was previously available in the https://github.com/upbound/provider-terraform repo (no longer accessible) covering:
1. Problem Description: Clear explanation of reconciliation blocking issues
2. Root Cause Analysis: Deep dive into the RWMutex locking mechanism that causes the blocking
3. Solutions & Workarounds:
- Persistent volume mounting (recommended solution)
- Plugin cache disabling for high concurrency
- Optimized concurrency settings
4. Monitoring & Diagnosis: Prometheus queries for tracking performance
5. Remote Git Repository Issues: Additional context on git-backed workspace limitations
6. Error Messages & Recovery: Common error patterns and resolutions
7. Best Practices: Production deployment recommendations
I have:
n/a
[contribution process]: …
> docs: Add troubleshooting docs
